### ISSUE TITLE
Add a logo

### ISSUE THREAD

**Issue by davetimmins** [colored-console/colored-console#14]
Something like 
![coloredconsole](https://cloud.githubusercontent.com/assets/1118347/4893848/6e1e9bde-63c8-11e4-8021-0eff4c350d03.png)

**Comment by blairconrad** [comment]
Regarding https://github.com/colored-console/colored-console/issues/14#issuecomment-63350175:  :heart_eyes:

**Comment by davetimmins** [comment]
Shall we go with that then seeing as there's been no other movement?

**Comment by adamralph** [comment]
This is the other one that was being considered (very rough sketch with many flaws)

![image](https://cloud.githubusercontent.com/assets/677704/11438604/3211974e-94f6-11e5-9db9-dc732d7ca82e.png)

**Comment by blairconrad** [comment]
Cute. Doesn't look bad scaled down, either.

**Comment by adamralph** [comment]
FWIW I did some tests to see how each proposal would look in the NuGet gallery.

### "Blocks"

##### Listing

![image](https://cloud.githubusercontent.com/assets/677704/14367092/69b30132-fd16-11e5-9388-47ac802f7f9d.png)

##### Package

![image](https://cloud.githubusercontent.com/assets/677704/14367101/79568f78-fd16-11e5-8b44-c4919c15cb96.png)

### "Splash"

##### Listing

![image](https://cloud.githubusercontent.com/assets/677704/14367063/35f4c4d4-fd16-11e5-90b5-4a8b1de56206.png)

##### Listing

![image](https://cloud.githubusercontent.com/assets/677704/14367074/4fdbb1c8-fd16-11e5-9a37-ae19b123b93d.png)

---

And here they are scaled down to icon size (neither are terribly good):

![image](https://cloud.githubusercontent.com/assets/677704/14367450/786cb89c-fd18-11e5-9997-7e25fc6ede5e.png)

**Comment by adamralph** [comment]
Actually the icons don't look too bad now that I look at them on a proper screen (that's the last time I assess icons whilst looking at my HTPC screen :blush:).

**Comment by davetimmins** [comment]
I think both concepts are fine and either is better than having nothing as it will stand out from the sea of the default NuGet logo. Whichever gets picked I'd make the following tweaks.

**Splat**
- needs a halo around >_ for display on dark theme
- reduce kerning on >_
- make splat slightly larger and reduce whitespace between it and >_

**Blocks**
- would prefer more vibrant colours and greater contrast
- alignment of characters needs to be improved (mainly last line)
- would be worth seeing what different fonts / font weights look like

In terms of choosing one (I'm assuming there are no other options on offer?) I tried a while back to gauge public opinion and got pretty much no feedback. So does anyone really not like a design? If so then lets use the other one.

**Comment by blairconrad** [comment]
Everyone loves splat!

**Comment by adamralph** [comment]
> alignment of characters needs to be improved (mainly last line)

Blocks was thrown together in minutes, as a concept. If it gets the go ahead then it will get all the necessary polish.

I like Splat, and I think it represents the project better than Blocks, but I think Blocks is better technically. 

In it's current form, I can't see a way to make Splat portable between dark and light backgrounds. A halo around `> _` sounds like it would change the logo significantly. I guess we could have dark and light versions with the light version having `> _` in white. Many other logos do this, e.g. [Nancy](https://github.com/NancyFx/Nancy.Portfolio).

Is the paint splash original art? If not, we need to verify that we're allowed to use it and that the source is available in adequate format (ideally as a vector image).

One thing that disturbs me a bit in Splat is the complexity of the paint splash itself. Simplicity usually works best for recognisability, and it also scales better, with complexity blurring out as you approach icon size. Having said that, Blocks doesn't scale down too well either. Whilst it is simple, there are a lot of characters and colours.

It would be interesting to take the concept of Splat, i.e. a prompt, cursor and colours, and try and create a simplified logo from it. Perhaps the two concepts of Splat and Blocks could even blend into each other?

I'll see if I can get some samples of Blocks with more vibrant colours and alternate fonts/weights.

I don't want to spend too much time on this, but I fear I already am :smile:. As you say, it's better to have something than nothing. Mind you, we did leave this thread dangling for 4 months with no movement so I guess we're not in a huge rush anyway.

**Comment by davetimmins** [comment]
> Is the paint splash original art? 

Yes, Splat is a Dave Timmins original :grin:
