### ISSUE TITLE
Support DNX with target dnxcore50 and .NET Core

### ISSUE THREAD

**Issue by giggio** [colored-console/colored-console#56]

**Comment by davetimmins** [comment]
Do you have any idea what is involved for this? I haven't really looked much at the new targets.

**Comment by adamralph** [comment]
It's still a moving target, but this blog post series helps http://blog.marcgravell.com/2015/11/the-road-to-dnxpart-3.html

**Comment by adamralph** [comment]
btw - @giggio, thanks for raising :smile:

**Comment by giggio** [comment]
Most of your code should be easily portable.
Better than supporting .NET Core, supporting the new .NET Platform Standard would be even better: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md

**Comment by adamralph** [comment]
Given the gut wrenching breaking changes from RC to RC, I think we should wait for RTM before doing this.

After all, there's not a huge amount to this package, so current .NET core shifting sands masochists can satisfy themselves by copying and pasting the code for now.

**Comment by davetimmins** [comment]
Sounds fair

**Comment by giggio** [comment]
Agreed.

**Comment by adamralph** [comment]
This is all set to change with .NET Core so I don't think it's worth investing any time in this. I also think that, ultimately, support for all platforms will be provided via support for the relevant [.NET Standard](https://gist.github.com/davidfowl/8939f305567e1755412d6dc0b8baf1b7), so I don't think explicit support for anything other than net45 will ever be a thing in ColoredConsole. For that reason, I'm leaning towards closing this. We can raise an issue to support the relevant .NET Standard after RTM.

**Comment by davetimmins** [comment]
Do it, the whole messaging and toing and froing around this isn't worth the effort. Best waiting until RTM and then the subsequent tooling support.
