### ISSUE TITLE
Parsed Console Colors from a string

### ISSUE THREAD

**Issue by Jaben** [colored-console/colored-console#70]
Please add a small DSL that allows changing the console colors directly inside the strings:

The parsed colors allow a simpler way to deal with complex color switching:

```
@DARKGRAY@*** @DARKCYAN@[@CYAN@AppName @WHITE@v1.9@DARKCYAN@] @DARKGRAY@***

e.g. #69

**Comment by davetimmins** [comment]
v1.0.0 released, thanks @Jaben 

https://www.nuget.org/packages/ColoredConsole
https://github.com/colored-console/colored-console/releases/tag/1.0.0
https://twitter.com/davetimmins/status/930613130509479937
