### ISSUE TITLE
Build errors?

### ISSUE THREAD

**Issue by D4nGuerrero** [colored-console/colored-console#71]
![image](https://user-images.githubusercontent.com/20586092/31137738-b7806450-a831-11e7-9fc8-831e9c791735.png)

**Comment by davetimmins** [comment]
Given that the CI build still works this seems more environmental. I know it doesn't work if you nly have VS2017 but did you also go through the https://github.com/colored-console/colored-console/blob/dev/how_to_build.md doc?

**Comment by D4nGuerrero** [comment]
Yes I went through the guide and installed choco + scriptcs
Windows

Ensure you have .NET framework 4.5 installed.

Ensure you have scriptcs 0.13.3 or later installed.

Using a command prompt, navigate to your clone root folder and execute:

build.bat

**Comment by davetimmins** [comment]
OK, the build probably needs updating anyway as the currently lib used (Bau) is no longer maintained.

**Comment by davetimmins** [comment]
Working again after #72
